### ISSUE TITLE
How to install ocst ? 

### ISSUE THREAD

**Issue by xulunfan** [freuk/ocst#1]
Hi! There isn't exist default.nix , I don't know how to install ocst.

00:12:31[xlf@master ~/Desktop/obps/ocst]$ make
nix-shell --run "topkg doc --docflags='-g ltxhtml.cma'"
error: getting status of '/home/xlf/Desktop/obps/ocst/default.nix': No such file or directory
make: *** [doc]  Error 1

Thanks.

**Comment by freuk** [comment]
The fix to this issue, https://github.com/freuk/obps/issues/1 will provide you with ocst packaging.
